validation:
  uid:
    not_found: 'Указанный идентификатор не найден'
  login:
    not_found: 'Пользователь с таким логином не найден'
    passwords_mismatch: 'Пароли не совпадают'
  common:
    field_absence: 'Недостаточно данных для обработки'
  register:
    email_exists: 'Пользователь с таким email уже зарегистрирован'
    email_invalid: 'Указанный email не прошёл проверку'
    lang: 'Использованы запрещенные символы'
    short_username: 'Слишком короткое имя пользователя'
    login_exists: 'Пользователь с таким логином уже зарегистрирован'
    password_absence: 'Один из паролей отсутствует'
    weak_password: 'Слишком слабый пароль'
    censor_words: 'Логин содержит запрещенные слова'
    not_valid_phone: 'Неверный формат номера телефона'
    phone_already_registered: 'Пользователь с данным номером телефона уже зарегистрирован'
  booking:
    previous_date: 'Указанная дата уже прошла'
  event: 
    admin_not_found: 'Указан неверный ID пользователя'
    date_not_found: 'Не указана дата'
    small_timing: 'Слишком маленький временной промежуток'
    already_exists: 'Событие на эту дату уже существует'
  course:
    invalid_date: 'Указана неверная дата'
    not_found: 'Указанный курс не найден'
    already_exists: 'Указанный курс уже существует'
  attendance:
    exists: 'Пользователь уже отмечен'
    uid_not_found: 'Пользователь не указан'
    too_big: 'Указанная дата ещё не наступила'
